name: Docker Publish

on:
  push:
    paths-ignore:
      - '.github/**'
  schedule:
    - cron: '1 1 3 * *'  

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - tag: "8"
          - tag: "11"
          - tag: "17"
          - tag: "21"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get date
        id: date
        run: echo "today=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          build-args: |
            JAVA_TAG=${{ matrix.tag }}
            RUNNER=github
          tags: |
            zcx2001/myjdk-libreoffice:${{ matrix.tag }}-${{ steps.date.outputs.today }}
            zcx2001/myjdk-libreoffice:${{ matrix.tag }}-latest